# Generated by Django 4.2.7 on 2023-11-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tharaapp', '0004_items_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
