# Generated by Django 4.1.7 on 2023-11-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tharaapp', '0005_rename_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('website_link', models.URLField()),
                ('phone_numbers', models.TextField(help_text='Enter each phone number on a new line, separating them with line breaks.')),
                ('image', models.ImageField(default=None, null=True, upload_to='Company/img')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('website_link', models.URLField()),
                ('phone_numbers', models.TextField(help_text='Enter each use on a new line, separating them with line breaks.', max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='Brand/img')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tharaapp.company')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tharaapp.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tharaapp.company'),
        ),
    ]
