# Generated by Django 4.1.7 on 2023-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tharaapp', '0008_dmcontact_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='cv_uploads/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
