# Generated by Django 4.1.7 on 2023-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tharaapp', '0009_cvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
