# Generated by Django 4.1.7 on 2023-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tharaapp', '0011_brand_email_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='email',
            field=models.CharField(default='default@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(default='default@example.com', max_length=255),
        ),
    ]
